config/routes.rb
Rails.application.routes.draw do
  resources :pokemons,          only: [:index]
  post 'pokemons/upload',      to: 'pokemons#upload'
  post 'pokemons/destroy_all', to: 'pokemons#destroy_all'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  require 'csv'
  def index
    @pokemons = Pokemon.all
  end

  def upload
    csv_path = File.join Rails.root, 'db', 'pokemon.csv'
    PokemonAddWorker.perform_async(csv_path)
    flash[:notice] = "Pokemons getting added to db"
    redirect_to pokemons_path
  end

  def destroy_all
    PokemonRemoveWorker.perform_async
    flash[:notice] = "Pokemons getting removed from db"
    redirect_to pokemons_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SidekiqPokemon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/index.html.erb
<h1>Pokemons</h1>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%#= link_to "See sidekiq stats", sidekiq_web_path %>

<%= form_tag pokemons_upload_path do %>
  <%= submit_tag "Import Pokemons" %>
<% end %>

<%= form_tag pokemons_destroy_all_path do %>
  <%= submit_tag "Delete Pokemons" %>
<% end %>

<table>
  <tr>
    <th>ID</th>
    <th>Pokemon</th>
    <th>Height</th>
    <th>Weight</th>
  </tr>
  <% @pokemons.each do |pokemon| %>
    <tr>
      <td><%=pokemon.species_id%></td>
      <td><%=pokemon.name%></td>
      <td><%=pokemon.height%></td>
      <td><%=pokemon.weight%></td>
    </tr>
  <%end%>
</table>